{{- if .Values.externalSecrets.enabled }}
{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-config" (include "ecom-shop-chart.serviceFullname" (dict "root" $ "name" $name))) $svc.externalSecret.targetSecretName }}
  labels:
    {{- include "ecom-shop-chart.serviceLabels" (dict "root" $ "name" $name) | nindent 4 }}
spec:
  refreshInterval: {{ default $.Values.externalSecrets.refreshInterval $svc.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ default $.Values.externalSecrets.secretStoreRef.kind $svc.externalSecret.secretStoreRef.kind }}
    name: {{ default $.Values.externalSecrets.secretStoreRef.name $svc.externalSecret.secretStoreRef.name }}
  target:
    name: {{ default (printf "%s-config" (include "ecom-shop-chart.serviceFullname" (dict "root" $ "name" $name))) $svc.externalSecret.targetSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $svc.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
