spring:
  application:
    name: user-service

  profiles:
    active: localhost

server:
  port: 5865

---

spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      uri: http://config-server:5859

---

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.110:5432/postgres?useSSL=false
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

cognito:
  hosted_ui_login_url: https://your-cognito-domain.auth.ap-southeast-1.amazoncognito.com/login
  hosted_ui_signup_url: https://your-cognito-domain.auth.ap-southeast-1.amazoncognito.com/signup